a = [('actions.edit.copy', 'Copy selection to clipboard'),
     ('actions.edit.cut', 'Cut selection to clipboard'),
     ('actions.edit.delete', 'Delete selection'),
     ('actions.edit.delete_line', 'Delete line under cursor'),
     ('actions.edit.delete_paragraph', 'Delete paragraph under cursor'),
     ('actions.edit.delete_sentence', 'Delete sentence under cursor'),
     ('actions.edit.delete_word', 'Delete word under cursor'),
     ('actions.edit.down', 'Move cursor down one row'),
     ('actions.edit.extend_again', 'Extend selection again in the same way'),
     ('actions.edit.extend_column', 'Extend selection to column <n>'),
     ('actions.edit.extend_down', 'Extend selection down one row'),
     ('actions.edit.extend_file_end', 'Extend selection to end of file'),
     ('actions.edit.extend_file_start', 'Extend selection to start of file'),
     ('actions.edit.extend_left', 'Extend selection left one column'),
     ('actions.edit.extend_line', 'Extend selection to include line <n>'),
     ('actions.edit.extend_line_down', 'Extend selection down one full line'),
     ('actions.edit.extend_line_end', 'Extend selection to end of line'),
     ('actions.edit.extend_line_start', 'Extend selection to start of line'),
     ('actions.edit.extend_line_up', 'Extend selection up one full line'),
     ('actions.edit.extend_page_down', 'Extend selection down one page'),
     ('actions.edit.extend_page_up', 'Extend selection up one page'),
     ('actions.edit.extend_paragraph_end',
      'Extend selection to the end of the current paragraph'),
     ('actions.edit.extend_paragraph_next',
     'Extend selection to the start of the next paragraph'),
     ('actions.edit.extend_paragraph_previous',
      'Extend selection to the start of the previous paragraph'),
     ('actions.edit.extend_paragraph_start',
     'Extend selection to the start of the current paragraph'),
     ('actions.edit.extend_right', 'Extend selection right one column'),
     ('actions.edit.extend_sentence_end',
     'Extend selection to the end of the current sentence'),
     ('actions.edit.extend_sentence_next',
      'Extend selection to the start of the next sentence'),
     ('actions.edit.extend_sentence_previous',
     'Extend selection to the start of the previous sentence'),
     ('actions.edit.extend_sentence_start',
      'Extend selection to the start of the current sentence'),
     ('actions.edit.extend_up', 'Extend selection up one row'),
     ('actions.edit.extend_word_left', 'Extend selection left one word'),
     ('actions.edit.extend_word_right', 'Extend selection right one word'),
     ('actions.edit.file_end', 'Move cursor to end of file (start of line)'),
     ('actions.edit.file_start', 'Move cursor to start of file'),
     ('actions.edit.find', 'Open Find dialog, optionally searching for text'),
     ('actions.edit.find_next', 'Select next Find result'),
     ('actions.edit.find_previous', 'Select previous Find result'),
     ('actions.edit.indent_less', 'Remove a tab stop of indentation'),
     ('actions.edit.indent_more', 'Add a tab stop of indentation'),
     ('actions.edit.jump_column',
     'Move cursor to column <n>'),
     ('actions.edit.jump_line', 'Move cursor to line <n>'),
     ('actions.edit.left', 'Move cursor left one column'),
     ('actions.edit.line_clone', 'Create a new line identical to the current line'),
     ('actions.edit.line_down', 'Move cursor to start of line below'),
     ('actions.edit.line_end', 'Move cursor to end of line'),
     ('actions.edit.line_insert_down', 'Insert line below cursor'),
     ('actions.edit.line_insert_up', 'Insert line above cursor'),
     ('actions.edit.line_start', 'Move cursor to start of line'),
     ('actions.edit.line_swap_down', 'Swap the current line with the line below'),
     ('actions.edit.line_swap_up', 'Swap the current line with the line above'),
     ('actions.edit.line_up', 'Move cursor to start of line above'),
     ('actions.edit.move_again', 'Move cursor again in the same way'),
     ('actions.edit.page_down', 'Move cursor down one page'),
     ('actions.edit.page_up', 'Move cursor up one page'),
     ('actions.edit.paragraph_end', 'Move cursor to the end of the current paragraph'),
     ('actions.edit.paragraph_next', 'Move cursor to the start of the next paragraph'),
     ('actions.edit.paragraph_previous',
     'Move cursor to the start of the previous paragraph'),
     ('actions.edit.paragraph_start',
     'Move cursor to the start of the current paragraph'),
     ('actions.edit.paste', 'Paste clipboard at cursor'),
     ('actions.edit.paste_match_style', 'Paste clipboard without style information'),
     ('actions.edit.print', 'Open print dialog'),
     ('actions.edit.redo', 'Redo'),
     ('actions.edit.right', 'Move cursor right one column'),
     ('actions.edit.save', 'Save current document'),
     ('actions.edit.save_all', 'Save all open documents'),
     ('actions.edit.select_all', 'Select all text in the current document'),
     ('actions.edit.select_line', 'Select entire line <n>, or current line'),
     ('actions.edit.select_lines', 'Select entire lines from <a> to <b>'),
     ('actions.edit.select_none', 'Clear current selection'),
     ('actions.edit.select_paragraph', 'Select the entire nearest paragraph'),
     ('actions.edit.select_sentence', 'Select the entire nearest sentence'),
     ('actions.edit.select_word', 'Select word under cursor'),
     ('actions.edit.selected_text', 'Get currently selected text'),
     ('actions.edit.selection_clone', 'Insert a copy of the current selection'),
     ('actions.edit.sentence_end', 'Move cursor to the end of the current sentence'),
     ('actions.edit.sentence_next', 'Move cursor to the start of the next sentence'),
     ('actions.edit.sentence_previous',
     'Move cursor to the start of the previous sentence'),
     ('actions.edit.sentence_start',
      'Move cursor to the start of the current sentence'),
     ('actions.edit.undo', 'Undo'),
     ('actions.edit.up', 'Move cursor up one row'),
     ('actions.edit.word_left', 'Move cursor left one word'),
     ('actions.edit.word_right', 'Move cursor right one word'),
     ('actions.edit.zoom_in', 'Zoom in'),
     ('actions.edit.zoom_out', 'Zoom out'),
     ('actions.edit.zoom_reset', 'Zoom to original size')]
